version: '2'

services:
  xbtodemo:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    network_mode: host
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - "27017:27017"
    network_mode: host